services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    restart: always
    ports:
      - '8026:8000'

  validator:
    build:
      context: .
      dockerfile: Dockerfile.validator
    restart: always
