[book]
authors = ["Chainbound <admin@chainbound.io>"]
language = "en"
multilingual = false
src = "src"
title = "DATO Book"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.template]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
